name: 'TEST Code Review'

on:
  push:
    branches: ['main', 'master']
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch: {}

jobs:
  code_review:
    timeout-minutes: 10 # temp fix
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Enable Corepack before setting up Node
        run: corepack enable
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run unit tests
        run: yarn test --maxWorkers=2 --coverage
